module.exports = {
    COUNT_FIELD_ID: 'gw_count_fid',
    DATE_TIME_DRILL_LEVELS: ['year', 'quarter', 'month', 'week', 'day', 'hour', 'minute', 'second', 'iso_year', 'iso_week'],
    DATE_TIME_FEATURE_LEVELS: [
        'year',
        'quarter',
        'month',
        'week',
        'weekday',
        'day',
        'hour',
        'minute',
        'second',
        'iso_year',
        'iso_week',
        'iso_weekday',
    ],
    MEA_KEY_ID: 'gw_mea_key_fid',
    MEA_VAL_ID: 'gw_mea_val_fid',
    PAINT_FIELD_ID: 'gw_paint_fid',
    PIVOT_TABLE_DEFAULT_LIMIT: 20000,
    PIVOT_TABLE_COLUMN_LIMIT: 200,
    PIVOT_TABLE_ROW_LIMIT: 10000,
    PIVOT_TABLE_DEBUG: false,
    USE_DUCKDB: false,
    DUCKDB_DEBUG: false,
};
